---
- hosts: demo
  gather_facts: no
  roles:
    - docker
    - basic_tools

  tasks:
  #  - name: make file system for data volume
  #    become: true
  #    filesystem:
  #      fstype: ext4
  #      dev: /dev/sdb

  #  - name: Create mount directory
  #    become: true
  #    file:
  #      path: mnt/volume
  #      state: directory
  #      owner: ubuntu
  #      group: ubuntu

  #  - name: Mount volume
  #    become: true
  #    mount:
  #      path: mnt/volume
  #      src: /dev/sdb
  #      fstype: ext4
  #      state: mounted

    - name: generate keypair
      openssh_keypair:
        path: /home/ubuntu/.ssh/id_rsa
        size: 2048
