---
- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Create docker directory
  become: true
  file:
    path: /etc/docker
    state: directory

- name: Create config file
  become: true
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json

- name: install docker
  become: true
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
    force_apt_get: yes
